(function(root){
  "use strict";

  const C=root.YarnchaCalculations;
  if(!C)throw new Error("YarnchaCalculations must load before YarnchaCalculatorEngine.");
  const VERSION="2026.07.01-shared-wrapper";
  const YARN_NAME={Lace:"Lace",Fingering:"Fingering / Sock",Sport:"Sport",DK:"DK / Light Worsted",Worsted:"Worsted / Aran",Aran:"Worsted / Aran",Bulky:"Bulky","Super Bulky":"Super Bulky",Unknown:"Unknown"};
  const YARN_META={"Lace":["0","30+","1.5-2.25 mm","1.5-2.25 mm"],"Fingering / Sock":["1","19-29","2.25-3.25 mm","2.25-3.5 mm"],Sport:["2","14-18","3.25-3.75 mm","3.5-4.5 mm"],"DK / Light Worsted":["3","11-14","3.75-4.5 mm","4.5-5.5 mm"],"Worsted / Aran":["4","8-11","4.5-5.5 mm","5.5-6.5 mm"],Bulky:["5","6-7","5.5-8 mm","6.5-9 mm"],"Super Bulky":["6","0-5","8-15 mm","9-15 mm"],Unknown:["","","",""]};

  function num(value,name,min=0,allowZero=false){const number=Number(value);if(!Number.isFinite(number)||number<min||(!allowZero&&number===0))throw new Error(`${name} must be ${allowZero?"at least":"greater than"} ${min}.`);return number;}
  function round(value,digits=2){return C.round(value,digits);}
  function whole(value){return C.whole(value);}
  function result(config){const confidence=Math.max(0,Math.min(99,Number(config.confidence??90)));return {version:VERSION,toolId:config.toolId,name:config.name,confidence,warning:config.warning||(confidence<90?"Manual verification recommended.":""),formula:config.formula||["calculated by shared Yarncha calculation layer"],variables:config.variables||{},intermediates:config.intermediates||{},outputs:config.outputs||{},summary:config.summary||"",notes:config.notes||[]};}

  function unitConvert(amount,from,to){const out=C.convertUnit({amount,from,to}).convertedValue;return result({toolId:"unit",name:"Unit Converter",confidence:99,variables:{amount,fromUnit:from,toUnit:to},outputs:{convertedValue:round(out,4)},summary:`${round(amount,4)} ${from} = ${round(out,4)} ${to}.`});}
  function gaugeSwatchAdapter(input){const out=C.calculateGaugeSwatchPlan({...input,originalPatternStitchCount:input.patternCount,originalPatternRowCount:input.patternRowCount});const stitchDiff=(num(input.userStitches,"User gauge stitches")-num(input.patternStitches,"Pattern gauge stitches"))/num(input.patternStitches,"Pattern gauge stitches")*100;const rowDiff=(num(input.userRows,"User gauge rows")-num(input.patternRows,"Pattern gauge rows"))/num(input.patternRows,"Pattern gauge rows")*100;return result({toolId:"swatch",name:"Gauge / Swatch Calculator",confidence:Math.max(72,96-Math.abs(stitchDiff)*.8-Math.abs(rowDiff)*.5),variables:input,intermediates:{stitchPercentDifference:stitchDiff,rowPercentDifference:rowDiff,patternStitchesPerCm:out.patternStitchesPerCm,userStitchesPerCm:out.userStitchesPerCm},outputs:{adjustedStitches:whole(out.adjustedPatternStitches),adjustedRows:whole(out.adjustedPatternRows),stitchDifferencePercent:round(stitchDiff,2),rowDifferencePercent:round(rowDiff,2)},summary:`Use about ${whole(out.adjustedPatternStitches)} stitches and ${whole(out.adjustedPatternRows)} rows.`});}
  function needleHookAdjustment(input){const out=C.calculateToolAdjustment({patternGaugeStitchesPer10cm:input.targetGauge,userGaugeStitchesPer10cm:input.currentGauge});const current=num(input.currentToolMm,"Current tool size"),delta=String(out.suggestedDirection)==="larger"?.5:String(out.suggestedDirection)==="smaller"?-.5:0;return result({toolId:"tool-adjust",name:"Needle / Hook Adjustment",confidence:82,variables:input,intermediates:{suggestedDirection:out.suggestedDirection},outputs:{suggestedToolMm:round(current+delta,2),estimatedShiftMm:round(delta,2),direction:`${out.suggestedDirection} tool`},summary:out.explanation});}
  function garmentSectionResizer(input){const out=C.calculateGarmentSectionResize(input);return result({toolId:"garment",name:"Pattern / Garment Resizer",confidence:86,variables:input,intermediates:{scaleRatio:out.scaleRatio},outputs:{left:out.left,centre:out.centre,right:out.right,total:out.total},summary:`Suggested split: left ${out.left}, centre/back ${out.centre}, right ${out.right}. Total ${out.total}.`});}
  function blockingCalculator(input){const beforeWidth=num(input.beforeWidth,"Before width"),beforeLength=num(input.beforeLength,"Before length"),afterWidth=input.afterWidth===""||input.afterWidth===undefined?beforeWidth*(1+Number(input.growthPercent||0)/100):num(input.afterWidth,"After width"),afterLength=input.afterLength===""||input.afterLength===undefined?beforeLength*(1+Number(input.growthPercent||0)/100):num(input.afterLength,"After length");const out=C.calculateBlocking({beforeWidthCm:beforeWidth,beforeLengthCm:beforeLength,afterWidthCm:afterWidth,afterLengthCm:afterLength,currentWidthCm:beforeWidth,currentLengthCm:beforeLength});return result({toolId:"blocking",name:"Blocking Calculator",confidence:input.afterWidth&&input.afterLength?92:78,variables:input,intermediates:{widthChangePercent:out.widthGrowthPercent,lengthChangePercent:out.lengthGrowthPercent},outputs:{blockedWidth:round(out.predictedWidth,2),blockedLength:round(out.predictedLength,2),widthChangePercent:round(out.widthGrowthPercent,2),lengthChangePercent:round(out.lengthGrowthPercent,2)},summary:`Blocked size estimate: ${round(out.predictedWidth,1)} x ${round(out.predictedLength,1)}.`});}
  function hatBeanie(input){const out=C.calculateHatPlan({headCircumferenceCm:input.headCircumference,stitchGauge:input.stitchGauge,rowGauge:input.rowGauge||28,negativeEasePercent:input.negativeEasePercent,hatDepthCm:input.hatDepthCm||Number(input.headCircumference||56)*.36});return result({toolId:"hat",name:"Hat / Beanie Size Calculator",confidence:88,variables:input,outputs:{castOn:out.castOn,crownDiameter:round(Number(input.headCircumference||0)/Math.PI,2),suggestedDepth:round(input.hatDepthCm||Number(input.headCircumference||56)*.36,2),shapingMultiple:4},summary:`Cast on about ${out.castOn} stitches.`});}
  function sockCalculator(input){const out=C.calculateSockPlan({footCircumferenceCm:input.footCircumference,footLengthCm:input.footLength,stitchGauge:input.stitchGauge,rowGauge:input.rowGauge||42,negativeEasePercent:input.negativeEasePercent});return result({toolId:"sock",name:"Sock Calculator",confidence:84,variables:input,outputs:{castOn:out.sockStitches,heelStitches:out.heelStitches,toeStartLength:out.footBeforeToeCm,toeDecreaseStitches:out.sockStitches},summary:`Cast on about ${out.sockStitches} stitches.`});}
  function sleeveCalculator(input){const out=C.calculateSleeveStitchShaping({startStitches:input.startStitches,endStitches:input.endStitches,rowsAvailable:input.rowsAvailable,stitchesChangedPerShapingRow:1});return result({toolId:"sleeve",name:"Sleeve Calculator",confidence:88,variables:input,intermediates:{change:out.stitchChange,action:out.action},outputs:{action:out.action,stitchChange:out.stitchChange,rowsBetweenShaping:out.rowsBetweenShaping},summary:`${out.action} ${out.stitchChange} stitch(es) over ${input.rowsAvailable} rows.`});}
  function raglanCalculator(input){const neck=num(input.neckStitches,"Neck stitches"),target=num(input.targetStitches,"Target stitches"),rate=num(input.increasePerRound,"Increase stitches per round");const rounds=Math.ceil(Math.max(0,target-neck)/rate),yoke=neck+rounds*rate;return result({toolId:"raglan",name:"Raglan Calculator",confidence:82,variables:input,outputs:{increaseRounds:rounds,yokeStitches:yoke,overshoot:yoke-target},summary:`Plan ${rounds} raglan increase round(s).`});}
  function blanketCalculator(input){const out=C.calculateBlanketPlan({widthCm:input.width,lengthCm:input.length,stitchGauge:input.stitchGauge,rowGauge:input.rowGauge,yarnPerTenByTen:input.yarnPerTenByTen,safetyMargin:1.2});return result({toolId:"blanket",name:"Blanket Calculator",confidence:86,variables:input,outputs:{stitches:out.blanketStitches,rows:out.blanketRows,estimatedYarn:round(out.estimatedYarn,1)},summary:`Plan about ${out.blanketStitches} stitches x ${out.blanketRows} rows.`});}
  function flatCircleCalculator(input){const rounds=Array.from({length:Math.max(1,whole(input.rounds||1))},(_,i)=>{const out=C.calculateCircle({startingStitches:input.startStitches||6,roundNumber:i+1,method:input.method||"smooth",stitchType:input.stitchType||"sc"});return {round:i+1,stitchCount:out.totalStitches,instruction:out.instruction};});return result({toolId:"circle",name:"Circle Calculator",confidence:88,variables:input,outputs:{rounds,finalStitchCount:rounds.at(-1).stitchCount},summary:`Flat circle: ${rounds.length} round(s), ending with ${rounds.at(-1).stitchCount} stitches.`});}
  function amigurumiShapeGuide(input){if(String(input.shape||"").toLowerCase()==="cylinder"){const base=flatCircleCalculator({startStitches:input.baseStitches,rounds:input.increaseRounds,stitchType:"sc"}).outputs.rounds;const straight=Array.from({length:Math.max(0,whole(input.straightRounds||0))},(_,i)=>({round:base.length+i+1,stitchCount:base.at(-1).stitchCount,instruction:"sc around with no increases"}));return result({toolId:"amigurumi",name:"Amigurumi Shape Guide",confidence:82,variables:input,outputs:{rounds:[...base,...straight],finalStitchCount:base.at(-1).stitchCount},summary:`cylinder guide: ${base.length+straight.length} round(s).`});}const out=C.calculateAmigurumiPlan(input);return result({toolId:"amigurumi",name:"Amigurumi Shape Guide",confidence:82,variables:input,outputs:{maxStitchCount:out.maxStitchCount,estimatedRounds:out.estimatedRounds,finalStitchCount:out.maxStitchCount},summary:out.shapingSuggestion});}
  function grannySquarePlanner(input){const out=C.calculateGrannySquare({targetWidthCm:input.blanketWidth||input.targetSize,targetLengthCm:input.blanketLength||input.targetSize,squareSizeCm:Math.ceil((num(input.targetSize,"Target size")-Number(input.joiningAllowance||0))/num(input.sizePerRound,"Size per round"))*num(input.sizePerRound,"Size per round"),joiningAllowanceCm:input.joiningAllowance});const roundsNeeded=Math.max(1,Math.ceil((num(input.targetSize,"Target size")-Number(input.joiningAllowance||0))/num(input.sizePerRound,"Size per round")));return result({toolId:"granny",name:"Granny Square Size Planner",confidence:86,variables:input,intermediates:{columns:out.squaresAcross,rows:out.squaresDown},outputs:{roundsNeeded,estimatedSquareSize:out.effectiveSquareSize,columns:out.squaresAcross,rows:out.squaresDown,totalSquares:out.totalSquares},summary:`Make ${out.totalSquares} square(s).`});}
  function c2cBlanketCalculator(input){const out=C.calculateC2CBlanket({targetWidthCm:input.width,targetLengthCm:input.height,blockWidthCm:input.blockSize,blockHeightCm:input.blockSize});return result({toolId:"c2c",name:"C2C Blanket Calculator",confidence:86,variables:input,outputs:{increaseRows:out.increaseRows,plateauRows:out.middleRows,decreaseRows:out.decreaseRows,totalBlocks:out.totalBlocks,estimatedYarn:round(out.totalBlocks*Number(input.yarnPerBlock||0)*1.15,1)},summary:`C2C plan: increase ${out.increaseRows} row(s), work ${out.middleRows} plateau row(s), decrease ${out.decreaseRows} row(s).`});}
  function gridGenerator(input){const out=C.calculateGridPlan({widthStitches:input.width,heightRows:input.height,colours:input.colors});return result({toolId:"grid",name:"Grid Generator",confidence:94,variables:input,outputs:{columns:out.columns,rows:out.rows,totalCells:out.totalCells},summary:`Grid ready: ${out.columns} columns x ${out.rows} rows.`});}
  function stripeGenerator(input){const out=C.calculateStripePlan({totalRows:input.totalRows,colourSequence:Array.from({length:Math.max(1,whole(input.colors||1))},(_,i)=>`Color ${i+1}`)});return result({toolId:"stripe",name:"Stripe Generator",confidence:94,variables:input,outputs:{sequence:out.stripeList},summary:`${input.direction||"horizontal stripes"}: ${out.stripeCount} stripe section(s).`});}
  function colorPoolingPlanner(input){const out=C.calculateColourPooling({yarnColourRepeatLengthCm:input.colorRepeatLength,stitchLengthCm:Number(input.colorRepeatLength||1)/Number(input.stitchesPerRepeat||1),stitchesPerRow:input.rowWidth});const shift=Number(input.rowWidth||0)%Number(input.stitchesPerRepeat||1);const stability=shift===0?"stable vertical pooling":shift<=2||shift>=Number(input.stitchesPerRepeat||1)-2?"gentle diagonal pooling":"unstable pooling";return result({toolId:"pooling",name:"Color Pooling Planner",confidence:82,variables:input,intermediates:{poolingOffset:out.poolingOffset},outputs:{stability,shiftPerRow:shift},summary:`Pooling prediction: ${stability}.`});}
  function yarnEstimator(input){const out=C.calculatePatternYarnEstimate(input);return result({toolId:"yarn-estimator",name:"Yarn Estimator",confidence:84,variables:input,intermediates:{modifiedAmount:out.modifiedAmount,withSafety:out.withSafety,estimatedWeight:out.estimatedWeight},outputs:{estimatedYarn:round(out.withSafety,1),suggestedSkeinsTotal:out.suggestedSkeinsTotal,skeinsToBuy:out.skeinsToBuy,estimatedLeftover:round(out.estimatedLeftover,1),estimatedWeight:round(out.estimatedWeight,1)},summary:`Estimated yarn needed: ${round(out.withSafety,0)} length units. Suggested total skeins: ${out.suggestedSkeinsTotal}; buy ${out.skeinsToBuy}.`});}
  function yarnLeftoverEstimator(input){const out=C.calculateYarnLeftover({originalSkeinWeightGrams:input.originalSkeinWeight,originalSkeinLengthMeters:input.originalSkeinLength,leftoverWeightGrams:input.leftoverWeight});return result({toolId:"yarn-leftover",name:"Yarn Leftover Estimator",confidence:92,variables:input,outputs:{leftoverLength:round(out.leftoverMeters,1),percentRemaining:round(Number(input.leftoverWeight)/Number(input.originalSkeinWeight)*100,1),suggestions:out.possibleProjectSuggestions},summary:`You have about ${round(out.leftoverMeters,1)} length units left.`});}
  function yarnSubstitution(input){const requiredMeters=Number(input.patternLength||0)*Number(input.patternBalls||0)*(1+Number(input.gaugeDifferencePercent||0)/100);const out=C.calculateYarnSubstitution({requiredMeters,substituteMetersPer100g:Number(input.substituteLength||0)/100*100,patternMetersPer100g:Number(input.patternLength||0)/100*100,substituteSkeinGrams:100});const substituteBalls=Math.ceil(requiredMeters/num(input.substituteLength,"Substitute yarn length"));return result({toolId:"substitution",name:"Yarn Substitution Helper",confidence:80,variables:input,intermediates:{neededLength:requiredMeters,lengthDifferencePercent:out.lengthDifferencePercent},outputs:{substituteBalls,compatibilityScore:round(Math.max(0,100-Math.abs(out.lengthDifferencePercent)),1),neededLength:round(requiredMeters,1)},summary:`Buy about ${substituteBalls} substitute ball(s).`});}
  function yarnWeightConverter(input){const metersPer100g=Number(input.length||0)&&Number(input.grams||0)?Number(input.length)/Number(input.grams)*100:0;const out=C.calculateYarnWeight({wpi:input.wpi,metersPer100g});const category=YARN_NAME[out.estimatedYarnWeight]||out.estimatedYarnWeight;const meta=YARN_META[category]||YARN_META.Unknown;return result({toolId:"yarn-weight",name:"Yarn Weight Converter",confidence:out.confidence==="high"?90:82,variables:input,intermediates:{method:Number(input.wpi)>0?`${input.wpi} WPI`:`${round(metersPer100g,1)} length units per 100 weight units`},outputs:{category,cyc:meta[0],wpiRange:meta[1],needles:meta[2],hooks:meta[3]},summary:`Estimated yarn category: ${category}.`});}
  function castOnCalculator(input){const out=C.calculateCastOn({targetWidthCm:input.width,stitchesPerCm:Number(input.gauge)/Number(input.gaugeSpan||10),stitchRepeatMultiple:input.multiple,edgeStitches:input.edge});return result({toolId:"cast-on",name:"Cast On Calculator",confidence:88,variables:input,outputs:{castOnStitches:out.castOnStitches},summary:`Cast on about ${out.castOnStitches} stitches.`});}
  function increaseDecreasePlanner(input){const out=C.calculateIncreaseDecrease({currentStitches:input.current,targetStitches:input.desired,craft:input.craft});return result({toolId:"shaping",name:"Increase / Decrease Planner",confidence:86,variables:input,intermediates:{interval:out.spacing,action:out.action},outputs:{action:out.action,changeCount:Math.abs(out.difference),suggestedInterval:Math.floor(out.spacing),finalStitchCount:whole(input.desired)},summary:out.friendly});}
  function repeatCalculator(input){const out=C.calculateRepeat({totalStitches:input.total,repeatStitches:input.repeat,edgeStitches:input.edge});return result({toolId:"repeat",name:"Repeat Calculator",confidence:96,variables:input,intermediates:{workableCount:out.usableStitches},outputs:{fullRepeats:out.repeatCount,remainder:out.remainingStitches,edgeStitches:Number(input.edge||0)},summary:`${out.repeatCount} full repeat(s) fit after ${input.edge||0} edge stitch(es).`});}
  function rowRoundHelper(input){const out=C.calculateRowProgress({totalRows:input.total,currentRow:input.current});const repeat=Math.max(1,whole(input.repeat||1));const nextCheckpoint=Math.ceil((Number(input.current||0)+1)/repeat)*repeat;return result({toolId:"row-helper",name:"Row / Round Counter Helper",confidence:96,variables:input,intermediates:{remainingRows:out.rowsRemaining},outputs:{progressPercent:out.currentProgress,nextCheckpoint,rowsLeft:out.rowsRemaining},summary:`${out.currentProgress}% complete. Next repeat checkpoint: row/round ${nextCheckpoint}.`});}
  function basicCalculator(input){const out=C.basicMath(input.expression);return result({toolId:"basic",name:"Basic Calculator",confidence:99,variables:{expression:String(input.expression||"0")},outputs:{result:round(out.result,6)},summary:`Calculator result: ${round(out.result,6)}.`});}

  root.YarnchaCalculatorEngine={VERSION,constants:{GAUGE_BASE_SPAN_CM:10},reference:{SIZE_REFERENCE:C.SIZE_REFERENCE},unitConvert,gaugeSwatchAdapter,needleHookAdjustment,garmentSectionResizer,blockingCalculator,hatBeanie,sockCalculator,sleeveCalculator,raglanCalculator,blanketCalculator,flatCircleCalculator,amigurumiShapeGuide,grannySquarePlanner,c2cBlanketCalculator,gridGenerator,stripeGenerator,colorPoolingPlanner,yarnEstimator,yarnLeftoverEstimator,yarnSubstitution,yarnWeightConverter,castOnCalculator,increaseDecreasePlanner,repeatCalculator,rowRoundHelper,basicCalculator};
})(typeof window!=="undefined"?window:globalThis);
