import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const app=await readFile(new URL("../app.js",import.meta.url),"utf8");
const css=await readFile(new URL("../styles.css",import.meta.url),"utf8");
const learningPathItem=app.match(/function libraryLearningPathItemHtml\(path\)\{[\s\S]*?\n\}/)?.[0]||"";

assert.match(app,/function libraryPageHeroHtml/,"Library pages share one page hero");
assert.match(app,/function libraryCategoryCardHtml/,"Library category cards share one renderer");
assert.match(app,/getElementById\("library-back"\)\?\.addEventListener/,"detail pages do not abort Library bindings when the outer back button is omitted");
assert.match(app,/knowledge-hub-groups/,"Theory hub uses grouped knowledge navigation");
assert.match(app,/\["Beginner","Intermediate","Advanced"\]/,"learning paths are grouped by level");
assert.match(app,/const completed=total>0&&progress>=total,status=completed\?"Completed":progress>0\?"In progress":"Not started",action=completed\?"Review":progress>0\?"Continue":"Start"/,"Learning Path overview exposes one contextual next action");
assert.match(app,/onclick="openLibraryLearningPath\('\$\{escapeHtml\(path\.id\)\}'\)"/,"Learning Path overview uses a direct action binding");
assert.doesNotMatch(learningPathItem,/data-wiki-path-progress/,"Learning Path overview does not expose a second progress action");
assert.doesNotMatch(learningPathItem,/practiceTask/,"Learning Path overview does not render detailed practice descriptions");
assert.doesNotMatch(app,/wiki-hero card[^`]*<h2>Theory & Foundation/,"Theory view does not repeat its page heading in a card");
assert.match(app,/class="wiki-detail"/,"article detail uses a natural page container");
assert.doesNotMatch(app,/class="wiki-detail card"/,"article detail is not wrapped in a generic card");
assert.match(app,/class="wiki-more-actions"/,"low-priority article actions use an overflow menu");
assert.match(app,/Problem[\s\S]*Diagnosis[\s\S]*Resolution[\s\S]*Prevention/,"troubleshooting follows the required diagnostic hierarchy");
assert.match(app,/details class="wiki-maintenance"/,"low-priority article maintenance is collapsible");
assert.doesNotMatch(app,/wiki-notes card/,"private notes are not wrapped in a generic card");
assert.match(app,/libraryWikiFilters\.search=event\.target\.value;libraryWikiFilters\.path="All"/,"manual search clears hidden curated-path filtering");
assert.doesNotMatch(app,/>Visual learning</,"articles do not render the obsolete static Visual Learning gallery");
assert.match(app,/function visualReferenceSectionHtml/,"articles share a reusable private visual-reference section");
assert.match(app,/function visualReferenceGalleryHtml/,"uploaded references share a reusable responsive gallery");
assert.match(app,/No visual references yet\./,"articles without uploads use a compact empty state");
assert.match(app,/libraryVisualReferences/,"visual references persist per Library entry");
assert.match(app,/data-visual-upload/,"each article supports private image uploads");
assert.match(app,/data-visual-view[\s\S]*data-visual-edit[\s\S]*data-visual-delete/,"visual references preserve view, edit/replace, and delete actions");
assert.match(app,/snapshot\.libraryVisualReferences[\s\S]*reference\.assetId/,"visual references are included in workspace backups");
assert.match(app,/section class="wiki-overview-card card"/,"article overview groups related reading content into one warm Yarncha card");
assert.match(app,/\$\{visualReferenceSectionHtml\(entry\)\}[\s\S]*wiki-overview-card card/,"visual references are the first major content card after the article summary");
assert.match(css,/#library-view \.wiki-detail-grid section \{ padding:0; border:0/,"overview subsections use whitespace rather than individual cards or dividers");
assert.match(css,/#library-view \.diagnostic-groups h3 \{ font-family:var\(--font-heading\) !important/,"decision workflow headings use the display font");
assert.match(css,/#library-view \.wiki-maintenance summary \{[\s\S]*font-family:var\(--font-ui\)/,"maintenance metadata uses the UI font");
assert.match(css,/#library-view \.library-category-card h2[\s\S]*font-family:var\(--font-ui\)/,"interactive Library titles use the UI font");
assert.match(css,/@media \(max-width:760px\)[\s\S]*#library-view \.knowledge-hub-groups/,"Library knowledge navigation has a mobile layout");
assert.match(css,/#library-view \.visual-reference-gallery \{[^}]*repeat\(4/,"visual references use a compact desktop gallery");
assert.match(css,/#library-view \.learning-path-item \{[^}]*grid-template-columns:minmax\(0,1fr\) minmax\(108px,150px\) auto/,"Learning Paths use compact scan-friendly rows");
assert.match(css,/@media \(max-width:900px\)[\s\S]*visual-reference-gallery[^}]*repeat\(2/,"visual references use two columns on tablet");
assert.match(css,/@media \(max-width:760px\)[\s\S]*visual-reference-gallery[^}]*grid-template-columns:1fr/,"visual references use one column on mobile");

console.log("Library experience contract passed.");
