import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const app=await readFile(new URL("../app.js",import.meta.url),"utf8");
const css=await readFile(new URL("../styles.css",import.meta.url),"utf8");
const learningPathItem=app.match(/function libraryLearningPathItemHtml\(path\)\{[\s\S]*?\n\}/)?.[0]||"";

assert.match(app,/function libraryPageHeroHtml/,"Library pages share one page hero");
assert.match(app,/function libraryCategoryCardHtml/,"Library category cards share one renderer");
assert.match(app,/getElementById\("library-back"\)\?\.addEventListener/,"detail pages do not abort Library bindings when the outer back button is omitted");
assert.doesNotMatch(app,/wiki-hero[\s\S]*libraryWikiHubCardsHtml\(\)/,"Theory hub does not split the article library into homepage categories");
assert.match(app,/\["Beginner","Intermediate","Advanced"\]/,"learning paths are grouped by level");
assert.match(app,/const completed=total>0&&progress>=total,status=completed\?"Completed":progress>0\?"In progress":"Not started",action=completed\?"Review":progress>0\?"Continue":"Start"/,"Learning Path overview exposes one contextual next action");
assert.match(app,/onclick="openLibraryLearningPath\('\$\{escapeHtml\(path\.id\)\}'\)"/,"Learning Path overview uses a direct action binding");
assert.doesNotMatch(learningPathItem,/data-wiki-path-progress/,"Learning Path overview does not expose a second progress action");
assert.match(learningPathItem,/\$\{escapeHtml\(path\.practiceTask\)\}/,"Learning Path overview includes a concise editorial description");
assert.doesNotMatch(app,/wiki-hero card[^`]*<h2>Theory & Foundation/,"Theory view does not repeat its page heading in a card");
assert.match(app,/class="wiki-detail"/,"article detail uses a natural page container");
assert.doesNotMatch(app,/class="wiki-detail card"/,"article detail is not wrapped in a generic card");
assert.match(app,/class="wiki-more-actions"/,"low-priority article actions use an overflow menu");
assert.match(app,/Symptoms[\s\S]*Likely causes[\s\S]*Quick checks[\s\S]*Decision path[\s\S]*Fix[\s\S]*Prevention/,"troubleshooting follows the six-part editorial hierarchy");
assert.match(app,/wiki-decision-tree card"><p class="eyebrow">TROUBLESHOOTING<\//,"Troubleshooting reuses the shared Overview kicker treatment");
assert.match(app,/details class="wiki-maintenance"/,"low-priority article maintenance is collapsible");
assert.doesNotMatch(app,/wiki-notes card/,"private notes are not wrapped in a generic card");
assert.match(app,/libraryWikiFilters\.search=event\.target\.value;libraryWikiFilters\.path="All"/,"manual search clears hidden curated-path filtering");
assert.doesNotMatch(app,/>Visual learning</,"articles do not render the obsolete static Visual Learning gallery");
assert.match(app,/function visualReferenceSectionHtml/,"articles share a reusable private visual-reference section");
assert.match(app,/function visualReferenceGalleryHtml/,"uploaded references share a reusable responsive gallery");
assert.match(app,/No visual references yet\./,"articles without uploads use a compact empty state");
assert.match(app,/libraryVisualReferences/,"visual references persist per Library entry");
assert.match(app,/data-visual-upload/,"each article supports private image uploads");
assert.match(app,/data-visual-view[\s\S]*data-visual-edit[\s\S]*data-visual-delete/,"visual references preserve view, edit/replace, and delete actions");
assert.match(app,/snapshot\.libraryVisualReferences[\s\S]*reference\.assetId/,"visual references are included in workspace backups");
assert.match(app,/section class="wiki-overview-card card"/,"article overview groups related reading content into one warm Yarncha card");
assert.match(app,/\$\{visualReferenceSectionHtml\(entry\)\}[\s\S]*wiki-overview-card card/,"visual references are the first major content card after the article summary");
assert.match(css,/#library-view \.wiki-detail-grid section \{ padding:0; border:0/,"overview subsections use whitespace rather than individual cards or dividers");
assert.match(css,/#library-view \.wiki-detail-grid \{ display:grid; grid-template-columns:1fr; gap:var\(--library-content-gap\); max-width:72ch/,"article overview uses a single-column reading layout with controlled line length");
assert.match(css,/#library-view \.wiki-detail \{ max-width:820px/,"Library articles use a focused single-column document width");
assert.match(css,/#library-view \.diagnostic-groups h3 \{ font-family:var\(--font-heading\) !important/,"decision workflow headings use the display font");
assert.match(css,/#library-view \.wiki-related > h3,[\s\S]*font-size:var\(--library-section-heading-size\)/,"Library section headings share one heading size");
assert.match(css,/--library-section-heading-size:26px/,"Library article section heading size is centralised as a shared token");
assert.match(css,/#library-view \.related-content h2,/,"nested Related Tools headings use the shared section-heading system");
assert.match(css,/#library-view \.diagnostic-groups > section \{ padding:0; border:0/,"troubleshooting topics are not nested cards or bordered panels");
assert.match(css,/#library-view \.diagnostic-groups \{[^}]*width:100%; max-width:none; padding:0; border:0;[^}]*background:transparent/,"troubleshooting uses the full flat article width without an inner card");
assert.match(css,/#library-view \.wiki-related \.wiki-entry-card \{[^}]*grid-template-rows:1fr auto/,"related cards keep content and actions in stable rows");
assert.match(css,/#library-view \.wiki-related \.wiki-card-actions button \{[^}]*min-width:max-content[^}]*writing-mode:horizontal-tb/,"related card actions cannot collapse into vertical text");
assert.match(app,/data-wiki-note-save/,"private notes expose an explicit local Save action");
assert.match(css,/#library-view \.wiki-notes textarea \{[^}]*width:100%[^}]*min-height:150px/,"private note textarea stays comfortably inside its section");
assert.match(css,/#library-view \.wiki-note-actions \.secondary-button \{[^}]*border:1px solid var\(--text-primary\)/,"private note Save uses functional button styling");
assert.match(css,/#library-view \.wiki-maintenance summary \{[\s\S]*font-family:var\(--font-ui\)/,"maintenance metadata uses the UI font");
assert.match(app,/class="content-title library-content-title"/,"Library content titles use the shared semantic class");
assert.match(css,/@media \(max-width:760px\)[\s\S]*#library-view \.knowledge-hub-groups/,"Library knowledge navigation has a mobile layout");
assert.match(css,/#library-view \.visual-reference-gallery \{[^}]*repeat\(4/,"visual references use a compact desktop gallery");
assert.match(learningPathItem,/class="learning-path-item card"/,"Learning Paths use the shared card surface");
assert.match(css,/#library-view \.learning-path-list \{[^}]*grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/,"Learning Paths use a three-column desktop card grid");
assert.match(css,/#library-view \.learning-path-item \{[^}]*display:flex[^}]*flex-direction:column[^}]*min-height:280px/,"Learning Path cards keep their content and actions aligned");
assert.match(css,/#library-view \.library-page-title \{[^}]*font-family:var\(--font-heading\) !important[^}]*font-size:46px !important[^}]*line-height:1\.08 !important/,"Learning Paths page title uses the semantic display-title role");
assert.match(css,/#library-view \.library-major-section-title \{[^}]*font-family:var\(--font-heading\) !important[^}]*font-size:30px !important/,"Learning Path level headings use the semantic major-section role");
assert.match(css,/#library-view \.learning-path-item \.library-learning-path-title \{[^}]*font-family:var\(--font-heading\) !important[^}]*font-size:19px !important[^}]*font-weight:700 !important/,"Learning Path item titles use the compact Fraunces content-title role");
assert.match(css,/@media \(max-width:900px\)[\s\S]*visual-reference-gallery[^}]*repeat\(2/,"visual references use two columns on tablet");
assert.match(css,/@media \(max-width:900px\)[\s\S]*learning-path-list[^}]*repeat\(2/,"Learning Path cards use two columns on tablet");
assert.match(css,/@media \(max-width:760px\)[\s\S]*visual-reference-gallery[^}]*grid-template-columns:1fr/,"visual references use one column on mobile");
assert.match(css,/@media \(max-width:760px\)[\s\S]*learning-path-list[^}]*grid-template-columns:1fr/,"Learning Path cards use one column on mobile");

console.log("Library experience contract passed.");
